const characteristics = {
  brand: "Производитель",
  releaseYear: "Год релиза",
  displayDiagonal: "Диагональ экрана (дюйм)",
  countryOfOrigin: "Страна-производитель",
  storage: "Объем памяти",
  frameRate: "Частота обновления экрана",
  nfc: "NFC",
  esimSupport: "Поддержка eSIM",
  wirelessCharge: "Поддержка беспроводной зарядки",
  price: "Стоимость",
};

const productsSource = [{
  image: "4895.png",
  model: "Apple iPhone 12",
  brand: "Apple",
  releaseYear: "2020",
  displayDiagonal: "6,1",
  countryOfOrigin: "Китай",
  storage: "128 Гб",
  frameRate: "60 Гц",
  nfc: false,
  esimSupport: true,
  wirelessCharge: true,
  price: "81 990 ₽"
},
{
  image: "4897.png",
  model: "Xiaomi Mi 11 Lite",
  brand: "Xiaomi",
  releaseYear: "2021",
  displayDiagonal: "6,55",
  countryOfOrigin: "Китай",
  storage: "128 Гб",
  frameRate: "90 Гц",
  nfc: true,
  esimSupport: true,
  wirelessCharge: false,
  price: "27 490 ₽"
},
{
  image: "4603.png",
  model: "Samsung Galaxy A72",
  brand: "Samsung",
  releaseYear: "2021",
  displayDiagonal: "6,7",
  countryOfOrigin: "Вьетнам",
  storage: "128 Гб",
  frameRate: "90 Гц",
  nfc: true,
  esimSupport: false,
  wirelessCharge: true,
  price: "32 890 ₽"
},
{
  image: "4605.png",
  model: "Samsung Galaxy S21",
  brand: "Samsung",
  releaseYear: "2021",
  displayDiagonal: "6,2",
  countryOfOrigin: "Вьетнам",
  storage: "128 Гб",
  frameRate: "120 Гц",
  nfc: true,
  esimSupport: true,
  wirelessCharge: true,
  price: "74 990 ₽"
},
{
  image: "4607.png",
  model: "Apple iPhone Xr",
  brand: "Apple",
  releaseYear: "2018",
  displayDiagonal: "6,1",
  countryOfOrigin: "Китай",
  storage: "64 Гб",
  frameRate: "60 Гц",
  nfc: true,
  esimSupport: true,
  wirelessCharge: true,
  price: "47 990 ₽"
},
{
  image: "4609.png",
  model: "Realme 8 Pro",
  brand: "Realme",
  releaseYear: "2021",
  displayDiagonal: "6,4",
  countryOfOrigin: "Китай",
  storage: "128 Гб",
  frameRate: "60 Гц",
  nfc: true,
  esimSupport: false,
  wirelessCharge: false,
  price: "19 990 ₽"
}]

export {characteristics, productsSource};
